### ISSUE TITLE
Please add palettes support

### ISSUE THREAD

**Issue by denizzzka** [TurkeyMan/color#12]

**Comment by TurkeyMan** [comment]
How do you think this would work? A single colour value can't reasonably hold a pointer to it's palette, and arithmetic operators can't really work in a meaningful way.

I can't really imagine what API I can provide that would improve on just using a `ubyte` matrix (or whatever type) for the image, and keeping a palette of `RGB8[N]` off side...

**Comment by denizzzka** [comment]
> A single colour value can't reasonably hold a pointer to it's palette

Colorspace value? Why it can't hold name and index to it's palette?

**Comment by TurkeyMan** [comment]
Umm, so a paletted 'colour' is usually <= 8 bits (1-ish byte). If each colour stores a reference to a palette, a colour becomes ~16 bytes... and reference strategy is not clear. What does an image made with this type look like?

What are you asking about colourspace value? Colourspace would be a property of the palette entry colour format.

Perhaps I misunderstood what you're asking for... can you propose the solution that you imagine?

**Comment by denizzzka** [comment]
Huh! I am isn't familiar with color stuff. I am just need to convert sRGB color to pure 8 bit XTerm palette for https://github.com/denizzzka/dtiv

**Comment by TurkeyMan** [comment]
I see. Converting an image to paletted colour is not really a colour operation at all. It's more like a data compression problem.

**Comment by denizzzka** [comment]
In other hand, this is common task of color processing. Perhaps it makes sense to solve this problem in general, without specifying the palette and the number of bits.

**Comment by TurkeyMan** [comment]
yeah, but my point is, it's not really a colour problem. i don't know if this really belongs in a module called 'colour'. it's more of an image processing problem.

**Comment by denizzzka** [comment]
Wait a minute! :-) Palette (indexed?) colour is a colour. And it can be converted (with losses) into another color type. That why this problem belongs in this module.

**Comment by TurkeyMan** [comment]
It's not a colour, it's a colour index. It's a numeric offset into a table, and carries no colour information at all by itself.
Also, converting an image is a problem that relates to a whole image, not a single colour value.

It's fairly easy to do what you want; for each pixel in the image, compare the 3d vector distance from each colour in the palette, a decent palette index is the entry with the shortest distance.

**Comment by denizzzka** [comment]
Ok. Thanks!
