### ISSUE TITLE
dmd.2_078_1/.dub/packages/color-0.0.5/color/std/experimental/normint.d(55,29): Deprecation: integral promotion not done for -cast(ubyte)255u, use '-transition=intpromote' switch or -cast(int)(cast(ubyte)255u)

### ISSUE THREAD

**Issue by timotheecour** [TurkeyMan/color#13]

**Comment by TurkeyMan** [comment]
Really? `ubyte` doesn't implicitly promote to `int`? WTF is this noise?!

**Comment by wilzbach** [comment]
> WTF is this noise?!

FYI:

https://dlang.org/changelog/2.078.0.html#fix16997
https://forum.dlang.org/post/ejpxdsgcdllsylkgqirs@forum.dlang.org

**Comment by TurkeyMan** [comment]
Fixed
