### ISSUE TITLE
dub: Switch default target type from sourceLibrary to library?

### ISSUE THREAD

**Issue by nordlow** [TurkeyMan/color#16]
Would it be possible to somehow integrate 

https://github.com/symmetryinvestments/color/commit/c309b30bdd9359d1499b0286eeec4c1c426560ba

upstream into `TurkeyMan/color`?

Or can reggae by adjusted to support

```
"targetType": "sourceLibrary"
```

so we don't need to maintain the fork https://github.com/symmetryinvestments/color

, @atilaneves?

FYI, @kinke.

**Comment by TurkeyMan** [comment]
Make a PR and I'll click the button :)

**Comment by nordlow** [comment]
I'm getting the error

```
Pull request creation failed. Validation failed: must be a collaborator
```

when trying to create the PR in the web ui of gitlab. Is this error message specific to web interactions?

**Comment by nordlow** [comment]
> I'm getting the error
> 
> ```
> Pull request creation failed. Validation failed: must be a collaborator
> ```
> 
> when trying to create the PR in the web ui of gitlab. Is this error message specific to web interactions?

Seems like that is the case because I managed to make the PR by pushing a locally created branch resulting in https://github.com/TurkeyMan/color/pull/17.

**Comment by nordlow** [comment]
Accompanying tags on both github and code.dlang.org are very welcome.
