### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by BlackEdder** [TurkeyMan/color#2]
When using the package with dub I get the following failure:  

  +----------------------------------------------------------------------
  | unittest failure
  +----------------------------------------------------------------------
  | File: ../../../.dub/packages/color-0.0.2/std/experimental/color/rgb.d
  | Line: 141
  +----------------------------------------------------------------------

**Comment by TurkeyMan** [comment]
Ah bummer. Sorry I just rushed a patch for you, I forgot to run with -unittest.
Just comment out the offending code, and I'll check this properly when I get some time?

**Comment by TurkeyMan** [comment]
`dub test` works for me on latest release.
