### ISSUE TITLE
Tag release and fix unittest

### ISSUE THREAD

**Issue by BlackEdder** [TurkeyMan/color#5]
I'd about ready to submit my plotting library to code.dlang.org. I'd like to use this colour library, but don't really want to tell people to depend on a master branch/version. Would it be possible to fix the failing tests ( #2 and #4 ; I'd be happy to submit a pull request with those commented out ) and tag a new release version?

**Comment by TurkeyMan** [comment]
Sure. I'll release an update very soon, and make sure it's all working at that time. You're welcome to submit a fix in the mean time.

**Comment by TurkeyMan** [comment]
Are you fixed here? There's been multiple releases since this bug...

**Comment by TurkeyMan** [comment]
Fairly certain tests are fixed, new tagged releases are available.
