### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [TurkeyMan/color#6]
If I add support for HCG color model, you accept it? 
https://github.com/acterhd/hcg-color

How I can test?

**Comment by TurkeyMan** [comment]
Hi, thanks for the contribution. I'm overseas right now with no computer. I'll review the patch when I get home in a couple of weeks. Sorry for the delay!

**Comment by TurkeyMan** [comment]
Oh sorry, I misunderstood, I thought this was a patch. I'll accept of it works well.
You can test with some reference implementation, maybe compare results to the one you linked?

**Comment by ghost** [comment]
How to I can test? i don't know. I don't know how to use D compiler.

**Comment by TurkeyMan** [comment]
I have implemented this, although I'm not sure why... maybe for fun? :)
